### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by FENG-MASTER** [Dengqlbq/ZhiHuSpider#1]
settings.py里修改好了本地数据库的帐号密码，也修改了爬虫用的邮箱帐号和密码。

而且按要求把数据库的表已经建立起来了，（我不保证类型完全一致，没有给出，我只能随便写个适合的

然而好像并不能用。

所有输出信息：

2017-11-21 17:08:27 [scrapy] INFO: Scrapy 1.1.0rc1 started (bot: zhihu)
2017-11-21 17:08:27 [scrapy] INFO: Overridden settings: {'SPIDER_MODULES': ['zhihu.spiders'], 'NEWSPIDER_MODULE': 'zhihu.spiders', 'BOT_NAME': 'zhihu'}
2017-11-21 17:08:27 [scrapy] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.logstats.LogStats',
 'scrapy.extensions.telnet.TelnetConsole']
2017-11-21 17:08:27 [scrapy] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.chunked.ChunkedTransferMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2017-11-21 17:08:27 [scrapy] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2017-11-21 17:08:27 [scrapy] INFO: Enabled item pipelines:
['zhihu.pipelines.ZhihuPipeline']
2017-11-21 17:08:27 [scrapy] INFO: Spider opened
2017-11-21 17:08:27 [scrapy] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2017-11-21 17:08:27 [scrapy] DEBUG: Telnet console listening on 127.0.0.1:6023
2017-11-21 17:08:27 [scrapy] ERROR: Error downloading <GET https://www.zhihu.com/>
Traceback (most recent call last):
  File "/home/qianzise/.local/lib/python3.5/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/qianzise/.local/lib/python3.5/site-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.5/dist-packages/scrapy/core/downloader/middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "/usr/local/lib/python3.5/dist-packages/scrapy/utils/defer.py", line 45, in mustbe_deferred
    result = f(*args, **kw)
  File "/usr/local/lib/python3.5/dist-packages/scrapy/core/downloader/handlers/__init__.py", line 65, in download_request
    return handler.download_request(request, spider)
  File "/usr/local/lib/python3.5/dist-packages/scrapy/core/downloader/handlers/http11.py", line 45, in download_request
    return agent.download_request(request)
  File "/usr/local/lib/python3.5/dist-packages/scrapy/core/downloader/handlers/http11.py", line 216, in download_request
    method, to_bytes(url, encoding='ascii'), headers, bodyproducer)
  File "/home/qianzise/.local/lib/python3.5/site-packages/twisted/web/client.py", line 1655, in request
    parsedURI.originForm)
  File "/home/qianzise/.local/lib/python3.5/site-packages/twisted/web/client.py", line 1432, in _requestWithEndpoint
    d = self._pool.getConnection(key, endpoint)
  File "/home/qianzise/.local/lib/python3.5/site-packages/twisted/web/client.py", line 1318, in getConnection
    return self._newConnection(key, endpoint)
  File "/home/qianzise/.local/lib/python3.5/site-packages/twisted/web/client.py", line 1330, in _newConnection
    return endpoint.connect(factory)
  File "/home/qianzise/.local/lib/python3.5/site-packages/twisted/internet/endpoints.py", line 2092, in connect
    self._wrapperFactory(protocolFactory)
  File "/home/qianzise/.local/lib/python3.5/site-packages/twisted/internet/endpoints.py", line 903, in connect
    EndpointReceiver, self._hostText, portNumber=self._port
  File "/home/qianzise/.local/lib/python3.5/site-packages/twisted/internet/_resolver.py", line 189, in resolveHostName
    onAddress = self._simpleResolver.getHostByName(hostName)
  File "/usr/local/lib/python3.5/dist-packages/scrapy/resolver.py", line 21, in getHostByName
    d = super(CachingThreadedResolver, self).getHostByName(name, timeout)
  File "/home/qianzise/.local/lib/python3.5/site-packages/twisted/internet/base.py", line 276, in getHostByName
    timeoutDelay = sum(timeout)
TypeError: 'float' object is not iterable
2017-11-21 17:08:27 [scrapy] INFO: Closing spider (finished)
2017-11-21 17:08:27 [scrapy] INFO: Dumping Scrapy stats:
{'downloader/exception_count': 1,
 'downloader/exception_type_count/builtins.TypeError': 1,
 'downloader/request_bytes': 355,
 'downloader/request_count': 1,
 'downloader/request_method_count/GET': 1,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2017, 11, 21, 9, 8, 27, 891165),
 'log_count/DEBUG': 1,
 'log_count/ERROR': 1,
 'log_count/INFO': 7,
 'scheduler/dequeued': 1,
 'scheduler/dequeued/memory': 1,
 'scheduler/enqueued': 1,
 'scheduler/enqueued/memory': 1,
 'start_time': datetime.datetime(2017, 11, 21, 9, 8, 27, 581399)}
2017-11-21 17:08:27 [scrapy] INFO: Spider closed (finished)

**Comment by Dengqlbq** [comment]
抱歉晚了几天才回，最近作业比较多。。
根据报错推测：
base.py的getHostByName函数中 timeoutDelay = sum(timeout)
timeout参数不是可迭代对象（例如：列表）导致。
疑惑的是项目代码中并没有对诸如timeout的参数进行设置，
猜测可能是python版本（3.6）不同或者由于环境不同（mac10.12.4)
上面的推论好像不怎么靠谱。。。。
或者你可以新建一个空project进行简单测试（比如start_requests函数）以便确定是不是项目的代码有问题

**Comment by FENG-MASTER** [comment]
我并没有找到timeout参数在哪里设置。

**Comment by FENG-MASTER** [comment]
Twisted版本问题，我降版本到16.6.0就可以了

**Comment by FENG-MASTER** [comment]
倒是出现了服务器 500 的错误，怎么解决？

**Comment by Dengqlbq** [comment]
这个一般是由于User-Agent导致的，你是修改了setting.py 里的DEFAULT_REQUEST_HEADERS或者在中间件里面修改了User-Agent么？
